users:
  admin:
    password: '654321'
    role: admin
  gaozheng:
    password: '123456'
    role: analyst
  lisi:
    password: '123456'
    role: user
  wangwu:
    password: '888888'
    role: user
